import { ResourceCatalogEntry } from "./types.js";

export const RESOURCE_CATALOG: ResourceCatalogEntry[] = [
  {
    id: "house.foundation.drums",
    kind: "compound_bundle",
    genre: "house",
    roles: ["drums"],
    energy: "medium",
    tempoRange: [122, 128],
    keySupport: "drums",
    source: "built_in",
    liveRef: "guided:house:drums",
    tags: ["starter", "foundation", "4-on-the-floor", "kick", "snare", "hats"],
    permissions: ["read", "import"],
  },
  {
    id: "house.foundation.bassline",
    kind: "pattern",
    genre: "house",
    roles: ["bass"],
    energy: "medium",
    tempoRange: [122, 128],
    keySupport: "transposable",
    source: "built_in",
    liveRef: "pattern:house-bass",
    tags: ["foundation", "groove", "low-end"],
    permissions: ["read", "import"],
  },
  {
    id: "house.foundation.chords",
    kind: "compound_bundle",
    genre: "house",
    roles: ["keys", "pad"],
    energy: "medium",
    tempoRange: [122, 128],
    keySupport: "transposable",
    source: "built_in",
    liveRef: "pattern:house-chords",
    tags: ["foundation", "stabs", "harmonic-bed"],
    permissions: ["read", "import"],
  },
  {
    id: "house.arrangement.core",
    kind: "scene_skeleton",
    genre: "house",
    roles: ["arrangement"],
    energy: "medium",
    tempoRange: [122, 128],
    keySupport: "fixed",
    source: "built_in",
    liveRef: "scenes:Intro>Verse 1>Verse 2>Build Up>Drop>Outro",
    tags: ["arrangement", "starter", "session-view"],
    permissions: ["read", "import"],
  },
  {
    id: "dnb.foundation.drums",
    kind: "compound_bundle",
    genre: "drum_n_bass",
    roles: ["drums"],
    energy: "high",
    tempoRange: [158, 174],
    keySupport: "drums",
    source: "built_in",
    liveRef: "guided:drum_n_bass:drums",
    tags: ["starter", "breakbeat", "kick", "snare", "hats"],
    permissions: ["read", "import"],
  },
  {
    id: "dnb.foundation.bassline",
    kind: "pattern",
    genre: "drum_n_bass",
    roles: ["bass"],
    energy: "high",
    tempoRange: [158, 174],
    keySupport: "transposable",
    source: "built_in",
    liveRef: "pattern:dnb-bass",
    tags: ["foundation", "sub", "neuro-lite"],
    permissions: ["read", "import"],
  },
  {
    id: "dnb.foundation.pads",
    kind: "pattern",
    genre: "drum_n_bass",
    roles: ["pad"],
    energy: "medium",
    tempoRange: [158, 174],
    keySupport: "transposable",
    source: "built_in",
    liveRef: "pattern:dnb-pads",
    tags: ["foundation", "atmosphere", "harmonic-bed"],
    permissions: ["read", "import"],
  },
  {
    id: "dnb.arrangement.core",
    kind: "scene_skeleton",
    genre: "drum_n_bass",
    roles: ["arrangement"],
    energy: "high",
    tempoRange: [158, 174],
    keySupport: "fixed",
    source: "built_in",
    liveRef: "scenes:Intro>Verse 1>Verse 2>Build Up>Drop>Outro",
    tags: ["arrangement", "starter", "session-view"],
    permissions: ["read", "import"],
  },
];
